
---
title: "Probability assignment"
author: "Muhammad Huzzaifa Khan"
---


Assignment 1:

```{r}
prob_Cscope <- 0.3
prob_NCscope <- 0.7

prob_time_Cscope <- 0.2
prob_Ntime_Cscope <- 0.8
prob_time_NCscope <- 0.6
prob_Ntime_NCscope <- 0.4



Prob_time_inter_Cscopes <- ( prob_Cscope * prob_time_Cscope )
Prob_time_inter_NCscope <- prob_NCscope * prob_time_NCscope
Prob_Ntime_inter_Cscope <- prob_Cscope * prob_Ntime_Cscope
Prob_Ntime_inter_NCscope <- prob_NCscope * prob_Ntime_NCscope

cat("P(T inter S) = ", Prob_time_inter_Cscopes , "\n")
cat("P(T inter NS) = ", Prob_time_inter_NCscope , "\n")
cat("P(NT inter S) = ", Prob_Ntime_inter_Cscope , "\n")
cat("P(NT inter NS) = ", Prob_Ntime_inter_NCscope , "\n")

cat("Total = ", Prob_time_inter_Cscopes+Prob_time_inter_NCscope+Prob_Ntime_inter_Cscope + Prob_Ntime_inter_NCscope  , "\n")

```

Assignment 2:

```{r}
Percentage_three_devices = 0.5
Percentage_atleast_two_devices = 7.3 + 3.3 + 8.8 + 0.5
Percentage_one_device = 27.8 + 42.3 + 10
cat("Percentage_three_devices = ", Percentage_three_devices , "\n")
cat("Percentage_atleast_two_devices = ", Percentage_atleast_two_devices , "\n")
cat("Percentage_one_device = ", Percentage_one_device , "\n")


```
Assignment 3:
```{r}
p_alarm_faulty <- 0.97
p_alarm_Nfaulty <- 0.01
p_faulty <- 0.04

p_alarms = (p_alarm_faulty*p_faulty)+((1 - p_faulty)*(p_alarm_Nfaulty) )

p_faulty_alarms = (p_alarm_faulty * p_faulty) / p_alarms 

 cat("p_faulty_alarm = ", p_faulty_alarms, "\n")
 
 p_Nfaulty_alarms = (p_alarm_Nfaulty * (1-p_faulty)) / p_alarms 

 cat("p_Nfaulty_alarms = ", p_Nfaulty_alarms, "\n")
 
 
 cat("These results show that in case the alarm is triggered, there is a possibility of about",p_Nfaulty_alarms * 100," % that the product is flawless and a probability of ",p_faulty_alarms * 100," % that the product is faulty.")
```

