---
title: "Randomized Controlled Trial"
author: "Huzzaifa khan"
---

```{r}
shop_df = readRDS("C:/Users/huzai/OneDrive/Documents/GitHub/tes/cdsba-cdx3745/content/Causal_Data_Science_Data/Causal_Data_Science_Data/abtest_online.rds")

View(shop_df)

```

Assignment: 1

```{r}

library(ggplot2)

check_cov_balanced_purchase <- ggplot(shop_df, aes(x=chatbot, y= purchase_amount, color = as.factor(chatbot))) +
  stat_summary(geom = "errorbar", 
               width = .5,
               fun.data = "mean_se", 
               fun.args = list(mult=1.96),
               show.legend = F) +
  labs(x = "chatbot", y = "purchase_amount", title = "treat chatboat for causal affect on purchase amount ")

check_cov_balanced_mob_devices <- ggplot(shop_df, aes(x=chatbot, y= mobile_device, color = as.factor(chatbot))) +
  stat_summary(geom = "errorbar", 
               width = .5,
               fun.data = "mean_se", 
               fun.args = list(mult=1.96),
               show.legend = F) +
  labs(x = "chatbot", y = "mobile_devices", title = "treat chatboat for causal affect on mobile devices ")



check_cov_balanced_prev_visit <- ggplot(shop_df, aes(x=chatbot, y= previous_visit, color = as.factor(chatbot))) +
  stat_summary(geom = "errorbar", 
               width = .5,
               fun.data = "mean_se", 
               fun.args = list(mult=1.96),
               show.legend = F) +
  labs(x = "chatbot", y = "previous_visit", title = "treat chatboat for causal affect on previous visit ")


check_cov_balanced_purchase
check_cov_balanced_mob_devices
check_cov_balanced_prev_visit

```

Assignment: 2

```{r}
lm_purchase_ate <- lm(purchase_amount~chatbot, data = shop_df)
summary(lm_purchase_ate)
```

Assignment: 3

```{r}
lm_purchase_cate <- lm(purchase_amount~chatbot * mobile_device, data = shop_df)
summary(lm_purchase_cate)
```

Assignment: 4

```{r}
log_lm <- glm(purchase ~ chatbot, family=binomial(link='logit'),data = shop_df)
summary(log_lm)
```