---
title: "Difference-in-Differences"
Author : "Huzzaifa Khan"
---

```{r}
hosp_data<- readRDS("C:/Users/huzai/OneDrive/Documents/GitHub/tes/cdsba-cdx3745/content/Causal_Data_Science_Data/Causal_Data_Science_Data/hospdd.rds")

View(hosp_data)
```

```{r}
#Assignment 1:

## Manually compute differences

# Step 1: Difference between treatment and control group BEFORE treatment

library(dplyr)
library(tidyverse)

before_treat_hosp <-hosp_data %>%
  filter(hospital <= 18, month < 3) %>% 
  pull(satis)

before_control_hosp <-hosp_data %>%
  filter(hospital > 18, month < 3) %>% 
  pull(satis)

diff_before_treat <- mean(before_treat_hosp) - mean(before_control_hosp)

# Step 2: Difference between treatment and control group AFTER treatment

after_treat_hosp <-hosp_data %>%
  filter(hospital <= 18, month >= 3) %>% 
  pull(satis)

after_control_hosp <-hosp_data %>%
  filter(hospital > 18, month >= 3) %>% 
  pull(satis)

diff_after_treat <- mean(after_treat_hosp) - mean(after_control_hosp)


# Step 3: Difference-in-differences. 

diff_diff_A <- diff_after_treat - diff_before_treat
sprintf("Estimate: %.2f", diff_diff_A)
```

```{r}
#Assignment 2:

summary(lm(satis ~ procedure + as.factor(month) + as.factor(hospital), data = hosp_data))

# as.factor(month) + as.factor(hospital) is more sensible to implement in the linear regression as our both regressor month and hospital are having a distinct categoreies. It will lead to more accurate estimation instead of usin month + hospital
```
